name: publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: prek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      - run: pnpm install --frozen-lockfile
      - run: prek run --all-files

  publish:
    needs: lint
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Configure Git authentication
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      - run: pnpm install --frozen-lockfile
      - name: bump version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          pnpm version minor
          git push
      - run: pnpm run build
      - run: pnpm publish --no-git-checks --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org
